#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
光之淨化閘門 (check_purity.py)
==============================
把光的法則變成可執行的檢查器：每站交付前必過淨化閘門。
過了才准上線——「一出生就乾淨，不做假帳」。

用法:
    python3 check_purity.py <站的路徑> [--dist]

檢查維度（光之淨化五律）:
  P1 乾淨  死圖源 / 佔位圖（pollinations、source.unsplash、picsum、placeholder）
  P2 乾淨  假評論 / 假證言（testimonial 假資料、sampleReview、fakeUser）
  P3 乾淨  假庫存 / 假數字（UI 硬編碼庫存、假瀏覽人數、假倒數）
  P4 合規  無依據促銷（劃線原價、% OFF、countdown——無 30 天最低價基準）
  P5 反指紋 AI 痕跡（generator meta、AI-generated、claude 註解、lorem、TODO/待補）
  P6 誠實  佔位文案（Lorem ipsum、"待補"、"coming soon" 空殼）

輸出: PASS / FAIL + 純淨分數 + 純淨證書 JSON（給控制台顯示）
"""
import json
import os
import re
import sys

# ── 雜質模式 ──────────────────────────────────────────────
PATTERNS = {
    "P1_dead_image_sources": [
        r"pollinations\.ai", r"source\.unsplash", r"picsum", r"placeholder\.com",
        r"placehold\.co", r"via\.placeholder",
    ],
    "P2_fake_reviews": [
        r"fake\s*[Rr]eview", r"sample\s*[Rr]eview", r"fake\s*[Uu]ser",
        r"testimonial\s*(?:data|list|samples?)",
    ],
    "P3_fake_stock_numbers": [
        r"stock\s*[:=]\s*\d{1,3}", r"inventory\s*[:=]\s*\d{1,3}",
        r"viewers?\s*[:=]", r"countdown", r"僅剩\s*\d", r"庫存\s*\d",
    ],
    "P4_unfounded_sale": [
        r"wasPrice", r"was_price", r"compareAtPrice", r"compare_at",
        r"%\s*OFF", r"saleLabel", r"原價", r"劃線", r"strikethrough",
    ],
    "P5_ai_fingerprints": [
        r'generator["\s=]+', r"AI-generated", r"Generated by AI", r"created by claude",
        r"claude\.ai", r"OpenAI", r"lorem", r"TODO", r"FIXME", r"待補",
    ],
    "P6_placeholder_copy": [
        r"lorem\s+ipsum", r"Lorem Ipsum", r"待補", r"coming soon", r"TBD",
        r"placeholder\s+text", r"Your text here",
    ],
}

SKIP_DIRS = {"node_modules", ".git", "dist", "build", "coverage", "wp-deployment", ".vercel"}
SKIP_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".woff", ".woff2",
             ".ttf", ".eot", ".map", ".lock", ".jsonl", ".md"}
# 鎖檔（package-lock/yarn.lock/pnpm-lock）是套件管理員自動產物，欄位名與雜質無關
SKIP_FILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "npm-shrinkwrap.json"}
# dist 檔在 --dist 模式才掃（壓縮後更難抓，但 meta/註解會留）

def walk_files(root, include_dist):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower()
            if ext in SKIP_EXTS or fn in SKIP_FILES:
                continue
            if not include_dist and os.sep + "dist" + os.sep in dirpath + os.sep:
                continue
            yield os.path.join(dirpath, fn)

def scan(root, include_dist):
    findings = []
    files = 0
    for fp in walk_files(root, include_dist):
        try:
            with open(fp, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
        except OSError:
            continue
        files += 1
        for key, patterns in PATTERNS.items():
            for pat in patterns:
                for m in re.finditer(pat, content, re.IGNORECASE):
                    # 記行號
                    line_no = content[:m.start()].count("\n") + 1
                    findings.append({
                        "check": key,
                        "file": os.path.relpath(fp, root),
                        "line": line_no,
                        "match": m.group(0)[:60],
                    })
    return files, findings

def main():
    if len(sys.argv) < 2:
        print("用法: python3 check_purity.py <站的路徑> [--dist]")
        sys.exit(2)
    root = os.path.abspath(sys.argv[1])
    include_dist = "--dist" in sys.argv
    if not os.path.isdir(root):
        print(f"❌ 路徑不存在: {root}")
        sys.exit(2)

    files, findings = scan(root, include_dist)

    # 彙整
    by_check = {}
    for f in findings:
        by_check.setdefault(f["check"], []).append(f)

    total = len(findings)
    score = max(0, 100 - total * 5)  # 每條雜質扣 5 分
    passed = total == 0

    print("=" * 56)
    print("光之淨化閘門 · 純淨檢查報告")
    print("=" * 56)
    print(f"站點       : {root}")
    print(f"掃描檔案   : {files} 個")
    print(f"雜質       : {total} 條")
    print(f"純淨分數   : {score}/100")
    print(f"判定       : {'✅ PASS 純淨，可上線' if passed else '❌ FAIL 有雜質，退回淨化'}")
    print("-" * 56)

    if findings:
        for key in ["P1_dead_image_sources", "P2_fake_reviews", "P3_fake_stock_numbers",
                    "P4_unfounded_sale", "P5_ai_fingerprints", "P6_placeholder_copy"]:
            items = by_check.get(key, [])
            if items:
                print(f"\n▸ {key}（{len(items)} 條）")
                for it in items[:8]:
                    print(f"   {it['file']}:{it['line']}  →  {it['match']!r}")
                if len(items) > 8:
                    print(f"   …還有 {len(items)-8} 條")
    else:
        print("每一維度都乾淨：無死圖源、無假評論、無假庫存、無假促銷、無 AI 指紋、無佔位。")

    # 純淨證書（給控制台）
    cert = {
        "site": os.path.basename(root.rstrip("/")),
        "checked_at": __import__("datetime").datetime.now().isoformat(),
        "files": files,
        "findings": total,
        "score": score,
        "passed": passed,
    }
    cert_path = os.path.join(root, "purity-certificate.json")
    with open(cert_path, "w", encoding="utf-8") as f:
        json.dump(cert, f, ensure_ascii=False, indent=2)
    print("-" * 56)
    print(f"純淨證書已寫入: {cert_path}")
    sys.exit(0 if passed else 1)

if __name__ == "__main__":
    main()
